org: kolyamba2105
app: sls-fp-api
service:
  name: sls-api

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    MONGO_URI:
      ${env:MONGO_URI, file(./env.yml):MONGO_URI}
    MONGO_USER:
      ${env:MONGO_USER, file(./env.yml):MONGO_USER}
    MONGO_PASSWORD:
      ${env:MONGO_PASSWORD, file(./env.yml):MONGO_PASSWORD}

functions:
  getUsers:
    handler: src/users/handlers/get-users.handler.handle
    events:
      - http:
          method: get
          path: users

  getUser:
    handler: src/users/handlers/get-user.handler.handle
    events:
      - http:
          method: get
          path: users/{id}

  deleteUser:
    handler: src/users/handlers/delete-user.handler.handle
    events:
      - http:
          method: delete
          path: users/{id}

  createUser:
    handler: src/users/handlers/create-user.handler.handle
    events:
      - http:
          method: post
          path: users

  updateUser:
    handler: src/users/handlers/update-user.handler.handle
    events:
      - http:
          method: patch
          path: users/{id}
